// LOCALHOST 

### Get all contacts 
GET http://localhost:8080/contacts

### Get contact by id 
GET http://localhost:8080/contacts/6742c8bc2377efc2fbfd0392

### Create contact 
POST http://localhost:8080/contacts 
content-type: application/json

{
"firstName":"Victory", 
"lastName":"Chibueze", 
"email":"victorychibueze699@gmail.com", 
"favoriteColor":"Navy blue", 
"birthday":"08/23/1998"
}

### Update contact 
PUT http://localhost:8080/contacts/6742ca172377efc2fbfd0393
content-type: application/json

{
"firstName":"Victory", 
"lastName":"Johnson", 
"email":"victorychibueze99@gmail.com", 
"favoriteColor":"Navy blue", 
"birthday":"07/23/1998"
}
### DELETE contact 
DELETE http://localhost:8080/contacts/6742ca172377efc2fbfd0393


// PRODUCTION Deploy

### Get all contacts 
GET https://cse341-project1-4pf5.onrender.com/contacts

### Get contact by id 
GET https://cse341-project1-4pf5.onrender.com/contacts/6742c8bc2377efc2fbfd0392

### Create contact 
POST https://cse341-project1-4pf5.onrender.com/contacts 
content-type: application/json

{
"firstName":"Ambless", 
"lastName":"Plug",
"email":"ambyplug@yahoo.com", 
"favoriteColor":"Brown", 
"birthday":"05/04/2000"
}

### Update contact 
PUT https://cse341-project1-4pf5.onrender.com/contacts/6742cb0f5bf84cdf85561140
content-type: application/json

{
"firstName":"Ambless", 
"lastName":"John",
"email":"ambyplug@yahoo.com", 
"favoriteColor":"Blue", 
"birthday":"05/04/2000"
}

### DELETE contact 
DELETE https://cse341-project1-4pf5.onrender.com/contacts/6742cb0f5bf84cdf85561140

